### ISSUE TITLE
Text doesn't show/update when writing a long line

### ISSUE THREAD

**Issue by ahota** [auxiliary/canvext#2]
If the line is long, the text doesn't scroll to let you view anything past the end of the input box. The cursor does go to the text past the end of the box, but you can't see it update. If you select the text, you can see it and create an annotation. Annotations also don't show up past the edge of the input box.

**Comment by auxiliary** [comment]
Fixed by limiting the user's input. Making the input size (and canvas) dynamic would require major changes.
